docker-compose-yaml: docker-compose.yml
environment_variables:
  git_sha: "true"
tasks:
  pre-rollout:
    - run:
        name: env variables
        command: env
        service: cli
    # - run:
    #     name: Push a pending status
    #     command: /app/scripts/github-build-status.sh pending
    #     service: cli
  post-rollout:
    - run:
        name: If this is a pull request, install the database.
        command: |
          if [[ -n ${LAGOON_PR_BASE_BRANCH} ]] && ! drush status --fields=bootstrap | grep -q "Successful"; then
              ./bin/drush -y site-install --account-pass=admin
          fi
        service: cli

    - run:
        name: drush updb
        command: ./bin/drush updb --yes
        service: cli
    - run:
        name: drush cim
        command: ./bin/drush cim --yes
        service: cli
    - run:
        name: drush sapi-i
        command: ./bin/drush sapi-i --yes
        service: cli
    - run:
        name: Push a pending status
        command: ./scripts/github-build-status.sh success
        service: cli
routes:
  insecure: Redirect
environments:
  master:
    cronjobs:
      - name: drush cron
        schedule: "H * * * *"
        command: drush cron
        service: cli
    routes:
      - frontend:
          - app.contribkanban.com:
              tls-acme: "true"
              insecure: Redirect
          - contribkanban.com:
              tls-acme: "true"
              insecure: Redirect
          - www.contribkanban.com:
              tls-acme: "true"
              insecure: Redirect
      - nginx:
          - api.contribkanban.com:
              tls-acme: "true"
              insecure: Redirect
