version: 2.1
commands:
  setup-build:
    steps:
    - run: sudo apt-get update && sudo apt-get install -y libpng-dev libjpeg62-turbo-dev
    - run:
        name: Install PHP Extensions
        command: sudo docker-php-ext-install gd
    - checkout
    - restore_cache:
        keys:
          - composer-{{ checksum "composer.lock" }}
          - composer-
          - yarn-{{ checksum "yarn.lock" }}
          - yarn-
  install-composer:
    steps:
      - run: composer global require "hirak/prestissimo:^0.3"
      - run:  composer install -n --prefer-dist
      - save_cache:
          paths:
            - ~/.composer/cache
          key: composer-{{ checksum "composer.lock" }}
  install-yarn:
    steps:
      - run: yarn install
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-{{ checksum "yarn.lock" }}

jobs:
  build_backend:
    docker:
      - image: circleci/php:7.2-cli
    working_directory: ~/repo
    steps:
      - setup-build
      - install-composer
  build_frontend:
    docker:
      - image: circleci/node:13
    working_directory: ~/repo
    steps:
      - checkout
      - install-yarn
      - run: yarn run frontend-build
  build_extension:
    docker:
      - image: circleci/node:13
    working_directory: ~/repo
    steps:
      - checkout
      - install-yarn
      - run: yarn run extension-build
  e2e_test:
    docker:
      - image: circleci/php:7.2-cli-node-browsers
        environment:
          REACT_APP_API_BASE_URL: 'http://127.0.0.1:8080'
    working_directory: ~/repo
    steps:
      - setup-build
      - install-composer
      - run:
          name: Install backend
          command: ./bin/drush -y site-install --account-pass=admin
      - run:
          name: Start builtin
          command: php -S 127.0.0.1:8080 -t web
          background: true
      - run:
          name: Wait for web server
          command: dockerize -wait http://127.0.0.1:8080 -timeout 120s
      - run:
          name: Fetch entrypoint
          command: curl http://127.0.0.1:8080/jsonapi
      - install-yarn
      - run: yarn run frontend-test
workflows:
  version: 2
  build:
    jobs:
      - build_backend
      - build_frontend
      - build_extension
  test:
    jobs:
      - e2e_test
