_core:
  default_config_hash: AyT9s8OUcclfALRE_imByOMgtZ19eOlqdF6zI3p7yqo
langcode: en
uuid: 00e8f2dd-5bef-40ab-b9df-e9cb85db1b7d
name: ContribKanban.com
mail: noreply@contribkanban.com
slogan: ''
page:
  403: /not-found
  404: /not-found
  front: /boards
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
