name: Drupdater Security

on:
  schedule:
    - cron: "0 4 * * *"  # every day at 04:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  drupdater-security:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/drupdater/drupdater-php8.3:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0  # full history is required to push the update branch
      - name: Run Drupdater
        run: /opt/drupdater/bin ${{ secrets.GITHUB_TOKEN }} --security
